apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cce21days-app11-huaweicloud
  namespace: default
spec:
  serviceName: "tank"
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cce21days-app11-huaweicloud
      failure-domain.beta.kubernetes.io/region: cn-north-1
      failure-domain.beta.kubernetes.io/zone: cn-north-1a
  template:
    metadata:
      labels:
        app: cce21days-app11-huaweicloud
        failure-domain.beta.kubernetes.io/region: cn-north-1
        failure-domain.beta.kubernetes.io/zone: cn-north-1a
    spec:
      affinity: {}
      containers:
      - image: swr.cn-north-1.myhuaweicloud.com/spring/tank:1.0.1
        imagePullPolicy: IfNotPresent
        name: container-0
        resources: {}
        volumeMounts:
        - mountPath: /tmp
          name: pvc-evs-example
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: default-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: pvc-evs-example
          persistentVolumeClaim:
            claimName: pvc-evs-auto-example
  updateStrategy:
    type: RollingUpdate
